function vb1 (data) {
  //   const B1 = d3.create('svg:g')
  //   B1.selectAll('g')
  //     .data(data)
  //     .enter()
  //     .append('rect')
  //     .attr('fill', 'brown')
  //     .attr('fill-opacity', d => d.opacity)
  //     .attr('style', 'stroke:#999;stroke-width:1.5;')
  //     .attr('x', d => d.x)
  //     .attr('y', d => d.y)
  //     .attr('height', d => d.height)
  //     .attr('width', d => d.width)
  //   B1.selectAll('text')
  //     .data(data)
  //     .enter()
  //     .append('text')
  //     .attr('y', d => d.y - 10)
  //     .attr('x', d => d.x)
  //     .text(d => {
  //       return d.text.map(t => t)
  //     })
  //   return B1.node()
}
export { vb1 }
